# Generated by Django 3.2.15 on 2022-10-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anique', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=50),
        ),
    ]
