# Generated by Django 3.2.15 on 2022-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anique', '0004_alter_skills_skill_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='link',
            new_name='live_link',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
